version: '2.1'
orbs:
  node: circleci/node@7.1.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: sudo npm install -g npm@8
      - run: npm run build
workflows:
  test_build:
    jobs:
      - build
